// <auto-generated />
namespace miniproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class slotidannotationapplied1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slotidannotationapplied1));
        
        string IMigrationMetadata.Id
        {
            get { return "201912021227051_slotidannotationapplied1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
